obj-y := gpu_sysfs.o

# Common files.
gpu_sysfs-y :=	gpu_sysfs_main.o \
		        gpu_sysfs_util.o


# Platform specific files.


# ==================================
# Start --------- Qualcomm ---------
#ifeq ($(CONFIG_MSM_KGSL),y)

gpu_sysfs-y +=	gpu_sysfs_target_kgsl.o
# Verify: target specific file is defined.
GPU_SYSFS_TARGET_FILE_DEFINED:=1

#endif
# End ---------- Qualcomm ----------
# ==================================


# ==================================
# Generate error if the TARGET
# specific file is not defined OR
# picked using the PLATFORM configs.
$(warning FIXME: CONFIG_MSM_KGSL='$(CONFIG_MSM_KGSL)')
$(warning FIXME: GPU_SYSFS_TARGET_FILE_DEFINED='$(GPU_SYSFS_TARGET_FILE_DEFINED)')
ifndef GPU_SYSFS_TARGET_FILE_DEFINED
$(warning **** Make sure target file is defined. \
               Check the TARGET and GPU configs in Makefile and Kernel Config. \
               Module won't work without target file. ****)
endif
